services:
    postgres:
        image: postgres:17-alpine
        environment:
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpass
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
